appname: test
traces: 1
charset: 'UTF8'
content_type: "text/plain"
logger: "File"
template: "template_toolkit"

session: 'YAML'

engines:
  template:
    template_toolkit:
      encoding: 'utf-8'
  serializer:
    json:
      pretty: 1
  logger:
    File:
      log_dir: "/tmp/testlogs"
  session:
    YAML:
      session_config:
        cookie_name: 'session.foo.dancer'
        expires: 86400

plugins:
  Foo:
    stuff: 42
